package ru.bgitu.components.updates.api.model

enum class InstallException {
    ERROR_UNKNOWN,
    ERROR_DOWNLOAD,
    ERROR_BLOCKED,
    ERROR_INVALID_APK,
    ERROR_CONFLICT,
    ERROR_STORAGE,
    ERROR_INCOMPATIBLE,
    ERROR_APP_NOT_OWNED,
    ERROR_INTERNAL_ERROR,
    ERROR_ABORTED,
    ERROR_APK_NOT_FOUND,
    ERROR_EXTERNAL_SOURCE_DENIED,
    ERROR_ACTIVITY_SEND_INTENT,
    ERROR_ACTIVITY_UNKNOWN
}